server:
  uri: "mongodb://localhost"
  host: "127.0.0.1"
  port: 27017
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

mongo:
  user: ""
  password: "" 
  dbName: escrum

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 43200m #30 days
  verificationCodeLength: 8