http:
  port: 27017
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

mongodbauth:
  databaseName: escrum

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 43200m #30 days
  verificationCodeLength: 8

  cors:
  allow_origins: ["http://localhost"]