name: UnderDevelopment

on:
  push:
    branches: developer
  pull_request:
    branches: developer

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unit Tests
        run: go test --short ./...

      - name: Create test db container
        run: docker run --rm -d -p 27019:27017 --name $(echo $TEST_CONTAINER_NAME) -e MONGODB_DATABASE=$(echo $TEST_DB_NAME) mongo:4.4-bionic

      - name: Integration Tests
        run: GIN_MODE=release go test -v ./tests/

      - name: Kill test db container
        run: docker stop $(echo $TEST_CONTAINER_NAME)

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -f Dockerfile -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .
             
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v1
      with:
        push: true
        tags: user/app:latest
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
